<?php

use Illuminate\Database\Seeder;

class JobsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        	DB::table('jobs')->delete();

    		DB::table('jobs')->insert([

    			['id'=>'1','title_en'=>'Assistant Marketing Manager','title_ar'=>'Assistant Marketing Manager','slug'=>'assistant-marketing-manager','department_id'=>'1','location_en'=>'Melbourne, Australia','location_ar'=>'Melbourne, Australia','education_en'=>'MBA or Master’s Degree','education_ar'=>'MBA or Master’s Degree','experience_en'=>'0 - 4 years','experience_ar'=>'0 - 4 years','job_description_en'=>'Distinctively fashion standardized communities vis-a-vis seamless applications. Authoritatively recaptiualize efficient supply chains without vertical initiatives. Progressively visualize strategic relationships with error-free processes. Credibly strategize fully tested outsourcing with functional e-markets. Dynamically evisculate user friendly architectures before cross-media experiences. Interactively disintermediate empowered data whereas distinctive human capital. Compellingly utilize.<br>Dynamically utilize intermandated materials through customized process improvements. Conveniently recaptiualize adaptive leadership before long-term high-impact functionalities. Completely incubate customer directed meta-services after economically sound imperatives. Distinctively evolve diverse applications for enterprise processes. Monotonectally disintermediate functionalized solutions rather than progressive leadership.','job_description_ar'=>'Distinctively fashion standardized communities vis-a-vis seamless applications. Authoritatively recaptiualize efficient supply chains without vertical initiatives. Progressively visualize strategic relationships with error-free processes. Credibly strategize fully tested outsourcing with functional e-markets. Dynamically evisculate user friendly architectures before cross-media experiences. Interactively disintermediate empowered data whereas distinctive human capital. Compellingly utilize.<br>Dynamically utilize intermandated materials through customized process improvements. Conveniently recaptiualize adaptive leadership before long-term high-impact functionalities. Completely incubate customer directed meta-services after economically sound imperatives. Distinctively evolve diverse applications for enterprise processes. Monotonectally disintermediate functionalized solutions rather than progressive leadership.','responsibilities_en'=>'Lorem ipsum dolor sit amet, consectetur elit.','responsibilities_ar'=>'Lorem ipsum dolor sit amet, consectetur elit.','job_status'=>'1'],

    			['id'=>'2','title_en'=>'Credit Assessment Manager','title_ar'=>'Credit Assessment Manager','slug'=>'credit-assessment-manager','department_id'=>'1','location_en'=>'Hamburg, Australia','location_ar'=>'Melbourne, Australia','education_en'=>'MBA or Master’s Degree','education_ar'=>'MBA or Master’s Degree','experience_en'=>'0 - 4 years','experience_ar'=>'0 - 4 years','job_description_en'=>'Distinctively fashion standardized communities vis-a-vis seamless applications. Authoritatively recaptiualize efficient supply chains without vertical initiatives. Progressively visualize strategic relationships with error-free processes. Credibly strategize fully tested outsourcing with functional e-markets. Dynamically evisculate user friendly architectures before cross-media experiences. Interactively disintermediate empowered data whereas distinctive human capital. Compellingly utilize.<br>Dynamically utilize intermandated materials through customized process improvements. Conveniently recaptiualize adaptive leadership before long-term high-impact functionalities. Completely incubate customer directed meta-services after economically sound imperatives. Distinctively evolve diverse applications for enterprise processes. Monotonectally disintermediate functionalized solutions rather than progressive leadership.','job_description_ar'=>'Distinctively fashion standardized communities vis-a-vis seamless applications. Authoritatively recaptiualize efficient supply chains without vertical initiatives. Progressively visualize strategic relationships with error-free processes. Credibly strategize fully tested outsourcing with functional e-markets. Dynamically evisculate user friendly architectures before cross-media experiences. Interactively disintermediate empowered data whereas distinctive human capital. Compellingly utilize.<br>Dynamically utilize intermandated materials through customized process improvements. Conveniently recaptiualize adaptive leadership before long-term high-impact functionalities. Completely incubate customer directed meta-services after economically sound imperatives. Distinctively evolve diverse applications for enterprise processes. Monotonectally disintermediate functionalized solutions rather than progressive leadership.','responsibilities_en'=>'Lorem ipsum dolor sit amet, consectetur elit.','responsibilities_ar'=>'Lorem ipsum dolor sit amet, consectetur elit.','job_status'=>'1'],

    			['id'=>'3','title_en'=>'Legal Counsel - Patent','title_ar'=>'Legal Counsel - Patent','slug'=>'legal-counsel-patent','department_id'=>'1','location_en'=>'Martinez, United States','location_ar'=>'Melbourne, Australia','education_en'=>'MBA or Master’s Degree','education_ar'=>'MBA or Master’s Degree','experience_en'=>'0 - 4 years','experience_ar'=>'0 - 4 years','job_description_en'=>'Distinctively fashion standardized communities vis-a-vis seamless applications. Authoritatively recaptiualize efficient supply chains without vertical initiatives. Progressively visualize strategic relationships with error-free processes. Credibly strategize fully tested outsourcing with functional e-markets. Dynamically evisculate user friendly architectures before cross-media experiences. Interactively disintermediate empowered data whereas distinctive human capital. Compellingly utilize.<br>Dynamically utilize intermandated materials through customized process improvements. Conveniently recaptiualize adaptive leadership before long-term high-impact functionalities. Completely incubate customer directed meta-services after economically sound imperatives. Distinctively evolve diverse applications for enterprise processes. Monotonectally disintermediate functionalized solutions rather than progressive leadership.','job_description_ar'=>'Distinctively fashion standardized communities vis-a-vis seamless applications. Authoritatively recaptiualize efficient supply chains without vertical initiatives. Progressively visualize strategic relationships with error-free processes. Credibly strategize fully tested outsourcing with functional e-markets. Dynamically evisculate user friendly architectures before cross-media experiences. Interactively disintermediate empowered data whereas distinctive human capital. Compellingly utilize.<br>Dynamically utilize intermandated materials through customized process improvements. Conveniently recaptiualize adaptive leadership before long-term high-impact functionalities. Completely incubate customer directed meta-services after economically sound imperatives. Distinctively evolve diverse applications for enterprise processes. Monotonectally disintermediate functionalized solutions rather than progressive leadership.','responsibilities_en'=>'Lorem ipsum dolor sit amet, consectetur elit.','responsibilities_ar'=>'Lorem ipsum dolor sit amet, consectetur elit.','job_status'=>'1'],
    		]);
    }
}
